# Generated by Django 3.2.8 on 2021-10-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_genre',
            field=models.CharField(default='science fiction', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_type',
            field=models.CharField(default='flash fiction', max_length=150),
            preserve_default=False,
        ),
    ]
