# Generated by Django 3.2.8 on 2021-10-11 15:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story_submission', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Story_Submission',
            new_name='StorySubmission',
        ),
    ]
