# Generated by Django 3.2.8 on 2021-10-11 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('story_submission', '0002_rename_story_submission_storysubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('likes', models.IntegerField(null=0)),
                ('dislikes', models.IntegerField(null=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story_submission.storysubmission')),
            ],
        ),
    ]
